const fs = require('fs');
const path = require('path');

const apiDir = path.join(__dirname, 'docs/api');

function getApiSidebar() {
  if (!fs.existsSync(apiDir)) return [];
  
  const folders = fs.readdirSync(apiDir).filter(f => fs.statSync(path.join(apiDir, f)).isDirectory());
  const root = { items: {}, files: null }; // Trie-like structure

  // Build Trie
  folders.forEach(folder => {
    const parts = folder.split('.');
    let current = root;
    parts.forEach((part, index) => {
      if (!current.items[part]) current.items[part] = { items: {}, files: null, label: part };
      current = current.items[part];
      // If this is the last part, this folder exists on disk, so it has files
      if (index === parts.length - 1) {
        current.files = `api/${folder}`;
      }
    });
  });

  // Convert Trie to Sidebar Items
  function convert(node) {
    const items = [];
    // If this node represents a real folder, add its files first
    if (node.files) {
      items.push({ type: 'autogenerated', dirName: node.files });
    }
    
    // Then add subcategories
    const sortedKeys = Object.keys(node.items).sort();
    sortedKeys.forEach(key => {
      const childNode = node.items[key];
      const convertedItems = convert(childNode);
      if (convertedItems.length > 0) {
          items.push({
            type: 'category',
            label: key,
            items: convertedItems,
            collapsible: true,
            collapsed: true
          });
      }
    });
    return items;
  }
  
  return convert(root);
}

const sidebars = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Guides',
      collapsible: true,
      collapsed: false,
      items: [
        { type: 'doc', id: 'guides/quick-start', label: 'Quick Start' },
        { type: 'doc', id: 'guides/game-architecture', label: 'Game Architecture' },
        { type: 'doc', id: 'guides/scripting-cheatsheet', label: 'Scripting Cheat Sheet' },
        { type: 'doc', id: 'guides/troubleshooting', label: 'Troubleshooting' },
      ],
    },
    {
      type: 'category',
      label: 'Code Reference',
      collapsible: true,
      collapsed: true,
      items: getApiSidebar(),
    },
  ],
};

module.exports = sidebars;
